version: '3.8'

services:
  
 
  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/main/webapp:/static
      # - ./docs/help:/documents
      - docs:/documents:ro
    depends_on:
      - app
      - docs
    ports:
      - '80:80'
      - '8081:8081'
    networks:
      - lavagna
      - frontend
  
  
  
  
  
  docs:
    build:
      context: .
      dockerfile: docs.Dockerfile
    networks:
      - frontend
      - lavagna
    volumes:
      - docs:/target/

  
  
  
  
  app:
    build:
      context: .
     
    # image: lavagna
    
       

    depends_on:
      mysql:
        condition: service_healthy
    networks: 
      - lavagna
      - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"


  mysql:
    image: mysql:5.7
    volumes:
      - db_vol:/var/lib/mysql
      - ./scheme:/docker-entrypoint-initdb.d
    networks:
      - lavagna
    environment:
       MYSQL_ROOT_PASSWORD: 54321
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-p54321']
      interval: 5s
      timeout: 5s
      retries: 10 
    
     
networks:
  lavagna:
  frontend:
    
volumes:
  db_vol:
  docs:
    